spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:mt_game} # 변수 없으면 mt_game 사용
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # ?? ?? update, ??? validate/none
    show-sql: true # ?? ???? ??? ??

  data:
    redis:
      host: localhost
      port: 6379